# Generated by Django 5.1.6 on 2025-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(verbose_name='Сипаттама'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(verbose_name='Аяқталу күні'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Аяқталды ма?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тақырып'),
        ),
    ]
